Polyclinic/Controllers/PolyclinicController.cs
using Polyclinic.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Polyclinic.Controllers
{
    public class PolyclinicController : Controller
    {
        private bd_polyclinicEntities db = new bd_polyclinicEntities();

        //[SecretCode]
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult RecordToDoctor()
        {
            return View();
        }

        public ActionResult ViewRecordsToDoctor()
        {
            return View();
        }

        public ActionResult ViewRecordsOnServices()
        {
            return View();
        }

        public ActionResult ViewTickets()
        {
            return View();
        }

        public ActionResult InDeveloping()
        {
            return View();
        }

        public ActionResult RecordOnService()
        {
            return View();
        }


        [AcceptVerbs(HttpVerbs.Post)]
        public JsonResult GetDataHandler(string command, string data1, string data2, string data3)
        {
            object responce = null;
            string cardNum = "";
            try
            {
                switch (command)
                {
                    case "posts":
                        List<object> posts = new List<object>();
                        var post = db.Specialty;
                        foreach (var p in post.ToList())
                        {
                            posts.Add(new { name = p.Discr, id = p.Spec_ID });
                        }
                        responce = posts.ToArray();
                        break;
                    case "doctors":
                        List<object> docs = new List<object>();
                        if (data1 == "speconly")
                        {
                            foreach (var staff in db.Spec.Select(x => x.Staff).ToList())
                            {
                                docs.Add(new
                                {
                                    name = staff.FIO,
                                    id = staff.Pers_ID
                                });
                            }
                            responce = docs.ToArray();
                            break;
                        }

                        int selPostId = data1 == null ? -1 : Int32.Parse(data1);
                        if (selPostId >= 0)
                        {
                            var selctedPost = db.Specialty.Include(s=>s.Staff1).FirstOrDefault(p=>p.Spec_ID == selPostId);
                            foreach (var staff in selctedPost.Staff1.ToList())
                            {
                                docs.Add(new {
                                    name = staff.FIO,
                                    id = staff.Pers_ID
                                });
                            }
                        }
                        else
                        {
                            foreach (var staff in db.Doctor.Select(x=>x.Staff).ToList())
                            {
                                docs.Add(new
                                {
                                    name = staff.FIO,
                                    id = staff.Pers_ID
                                });
                            }
                        }
                        responce = docs.ToArray();
                        break;
                    case "checkticket":
                        cardNum = data1;
                        responce = db.Reg_card.Any(x => x.Card_Num == cardNum);
                        break;
                    case "checkdocid":
                        var doc_ID = Int32.Parse(data1);
                        responce = db.Doctor.Any(x => x.Pers_ID == doc_ID);
                        break;
                    case "checkspecid":
                        var spec_ID = Int32.Parse(data1);
                        responce = db.Spec.Any(x => x.Pers_ID == spec_ID);
                        break;
                    case "doctorschedule":
                        List<object> docsRecs = new List<object>();
                        int docId = Int32.Parse(data1);
                        var doctoRrecords = db.Schedule.Include(x => x.Cabinet).
                            Where(s => s.Pers_ID == docId && s.Rec_card_ID == null);
                        foreach (var dRec in doctoRrecords)
                        {
                            docsRecs.Add(new
                            {
                                name = dRec.Doctor.Staff.FIO,
                                cabinet = dRec.Cabinet.Cab_Num,
                                time = dRec.Start_Date.ToString("yy-MM-dd H:mm:ss"),
                                scheduleid = dRec.Schedule_ID
                            });
                        }
                        responce = docsRecs.ToArray();
                        break;
                    case "recordtodoctor":
                        var sched = db.Schedule.Find(Int32.Parse(data2));
                        sched.Rec_card_ID = db.Reg_card.FirstOrDefault(x => x.Card_Num == data1).Rec_card_ID;
                        db.SaveChanges();
                        break;
                    case "viewdoctorsrecords":
                        List<object> docRecs = new List<object>();
                        int doc_Id = Int32.Parse(data1);
                        var docRrecords = db.Schedule
                            .Include(r => r.Cabinet)
                            .Include(r => r.Reg_card)
                            .Where(r => r.Pers_ID == doc_Id && r.Rec_card_ID != null);
                        foreach (var dRec in docRrecords)
                        {
                            docRecs.Add(new
                            {
                                name = dRec.Reg_card.FIO,
                                cabinet = dRec.Cabinet.Cab_Num,
                                time = dRec.Start_Date.ToString("yy-MM-dd H:mm:ss")
                            });
                        }
                        responce = docRecs.ToArray();
                        break;
                    case "viewspecrecords":
                        List<object> specRecs = new List<object>();
                        int spec_Id = Int32.Parse(data1);
                        var specRrecords = db.Rec_serv
                           .Include(r => r.Services)
                            .Include(r => r.Reg_card)
                            .Where(r => r.Services.Pers_ID == spec_Id);
                        foreach (var sRec in specRrecords)
                        {
                            specRecs.Add(new
                            {
                                name = sRec.Reg_card.FIO,
                                cabinet = sRec.Services.Cabinet.Cab_Num,
                                time = sRec.Date.Value.ToString("yyyy-MM-dd"),
                                service = sRec.Services.Discr,
                                price = sRec.Services.Price
                            });
                        }
                        responce = specRecs.ToArray();
                        break;
                    case "viewdoctickets":
                        List<object> tickRecs = new List<object>();
                        cardNum = data1;
                        var tickRrecords = db.Schedule.
                            Where(r => r.Reg_card.Card_Num == cardNum);
                        foreach (var dRec in tickRrecords)
                        {
                            tickRecs.Add(new
                            {
                                name = dRec.Doctor.Staff.FIO,
                                cabinet = dRec.Cabinet.Cab_Num,
                                time = dRec.Start_Date.ToString("yy-MM-dd H:mm:ss"),
                            });
                        }
                        responce = tickRecs.ToArray();
                        break;
                    case "viewservicetickets":
                        List<object> serTickRecs = new List<object>();
                        cardNum = data1;
                        var servTickRrecords = db.Rec_serv.Include(r => r.Services).Include(r=>r.Reg_card).
                            Where(r => r.Reg_card.Card_Num == cardNum);
                        foreach (var sRec in servTickRrecords)
                        {
                            serTickRecs.Add(new
                            {
                                service = sRec.Services.Discr,
                                name = sRec.Services.Spec.Staff.FIO,
                                cabinet = sRec.Services.Cabinet.Cab_Num,
                                time = sRec.Date.Value.ToString("yy-MM-dd H:mm:ss"),
                                price = sRec.Services.Price
                            });
                        }
                        responce = serTickRecs.ToArray();
                        break;
                    case "services":
                        List<object> servs = new List<object>();
                        var services = db.Services;
                        foreach (var serv in services.ToList())
                        {
                            servs.Add(new { name = serv.Discr, id = serv.Serv_ID });
                        }
                        responce = servs.ToArray();
                        break;
                    case "spec":
                        List<object> specs = new List<object>();
                        var servics = db.Services.Include(s => s.Spec);
                        var ser = servics.FirstOrDefault();
                        responce = new { name = ser.Spec.Staff.FIO, id = ser.Pers_ID };
                        break;
                    case "addservrecord":

Polyclinic/Views/Polyclinic/InDeveloping.cshtml
@{
    ViewBag.Title = "InDeveloping";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="alert alert-danger" role="alert">
    <p>Извините, раздел находится в разработке.</p>
</div>

Polyclinic/Views/Polyclinic/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-3">
        <div class="thumbnail">
            <div class="caption">
                <h3>Запись к врачу</h3>
                <p>Для того чтобы записаться к врачу...</p>
                <p>@Html.ActionLink("Записаться", "RecordToDoctor", "Polyclinic", new { @class = "btn btn-default" })</p>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="thumbnail">
            <div class="caption">
                <h3>Запись на услугу</h3>
                <p>Для того чтобы записаться на услугу...</p>
                <p>@Html.ActionLink("Записаться", "RecordOnService", "Polyclinic", new { @class = "btn btn-default" })</p>
            </div>
        </div>
    </div>
    <div class="col-md-3"></div>
</div>

Polyclinic/Views/Polyclinic/RecordOnService.cshtml
@{
    ViewBag.Title = "RecordOnService";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class='col-sm-8'>
        <div id="record-on-service-wizard">
            <ul>
                <li><a href="#tab1" data-toggle="tab">Введите номер карты</a></li>
                <li><a href="#tab2" data-toggle="tab">Выберете услугу</a></li>
                <li><a href="#tab3" data-toggle="tab">Выберете дату</a></li>
                <li><a href="#tab4" data-toggle="tab">Вы записаны</a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane" id="tab1">
                    <div class="control-group">
                        <input type="text" class="form-control" id="ticket-number">
                    </div>
                </div>
                <div class="tab-pane" id="tab2">
                    <div class="control-group">
                        <div class="dropdown">
                            <button id="service-selector" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="selector-title"></span>
                                <span class="caret"></span>
                            </button>
                            <ul id="service-menu" class="dropdown-menu" aria-labelledby="dLabel"></ul>
                        </div>
                    </div>
                </div>
                <div class="tab-pane" id="tab3">
                    <div class="row">
                        <div class='col-sm-4'>
                            <div class="form-group">
                                <div class='input-group date' id='date-selector'>
                                    <input type='text' class="form-control" />
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-calendar"></span>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>                
                </div>
                <div class="tab-pane" id="tab4">
                    <p>Пациент с номером карты {} записан на услугу {} к специалисту {}.</p>
                </div>
                <ul class="pager wizard">
                    <li class="previous first" style="display:none;"><a href="#">К началу</a></li>
                    <li class="previous"><a href="#">Назад</a></li>
                    <li class="next last" style="display:none;"><a href="#">К концу</a></li>
                    <li class="next"><a href="#">Далее</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

Polyclinic/Views/Polyclinic/RecordToDoctor.cshtml
@{
    ViewBag.Title = "RecordToDoctor";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class='col-sm-9'>
        <div id="record-to-doctor-wizard">
            <ul>
                <li><a href="#tab1" data-toggle="tab">Введите номер карты</a></li>
                <li><a href="#tab2" data-toggle="tab">Выберете специализацию</a></li>
                <li><a href="#tab3" data-toggle="tab">Выберете врача</a></li>
                <li><a href="#tab4" data-toggle="tab">Выберете дату</a></li>
                <li><a href="#tab5" data-toggle="tab">Вы записаны</a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane" id="tab1">
                    <div class="control-group">
                        <input type="text" class="form-control" id="ticket-number">
                    </div>
                </div>
                <div class="tab-pane" id="tab2">
                    <div class="control-group">
                        <div class="dropdown">
                            <button id="post-selector" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="selector-title"></span>
                                <span class="caret"></span>
                            </button>
                            <ul id="posts-menu" class="dropdown-menu" aria-labelledby="dLabel"></ul>
                        </div>
                    </div>
                </div>
                <div class="tab-pane" id="tab3">
                    <div class="control-group">
                        <div class="dropdown">
                            <button id="doctor-selector" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="selector-title"></span>
                                <span class="caret"></span>
                            </button>
                            <ul id="doctors-menu" class="dropdown-menu" aria-labelledby="dLabel"></ul>
                        </div>
                    </div>
                </div>
                <div class="tab-pane" id="tab4">
                    <table id="free-time" class="table table-bordered" data-height="300">
                        <thead>
                            <tr>
                                <th data-field="state" data-radio="true"></th>
                                <th data-field="cabinet">Кабинет</th>
                                <th data-field="time">Время</th>
                                <th data-field="name">ФИО доктора</th>
                                <th data-field="scheduleid" data-visible="false"></th>
                            </tr>
                        </thead>
                        <tbody class="free-time-body">
                        </tbody>
                    </table>
                </div>
                <div class="tab-pane" id="tab5">
                    <p>Вы записаны на прием к врачу.</p>
                </div>
                <ul class="pager wizard">
                    <li class="previous first" style="display:none;"><a href="#">К началу</a></li>
                    <li class="previous"><a href="#">Назад</a></li>
                    <li class="next last" style="display:none;"><a href="#">К концу</a></li>
                    <li class="next"><a href="#">Далее</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

Polyclinic/Views/Polyclinic/ViewRecordsOnServices.cshtml
@{
    ViewBag.Title = "ViewRecordsOnServices";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class='col-sm-7'>
        <div id="viewer-records-to-spec-wizard">
            <ul>
                <li><a href="#tab1" data-toggle="tab">Выберете специалиста</a></li>
                <li><a href="#tab2" data-toggle="tab">Записи на услугу</a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane" id="tab1">
                    <div class="control-group">
                        <div class="dropdown">
                            <button id="doctor-selector" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="selector-title spec"></span>
                                <span class="caret"></span>
                            </button>
                            <ul id="doctors-menu" class="dropdown-menu" aria-labelledby="dLabel"></ul>
                        </div>
                    </div>
                </div>
                <div class="tab-pane" id="tab2">
                    <table id="spec-records" class="table table-bordered" data-height="300">
                        <thead>
                            <tr>
                                <th data-field="service">Усдуга</th>
                                <th data-field="cabinet">Кабинет</th>
                                <th data-field="time">Дата</th>
                                <th data-field="name">ФИО пациента</th>
                                <th data-field="price">Цена</th>
                            </tr>
                        </thead>
                        <tbody class="spec-records-body"></tbody>
                    </table>
                </div>
                <ul class="pager wizard">
                    <li class="previous first" style="display:none;"><a href="#">К началу</a></li>
                    <li class="previous"><a href="#">Назад</a></li>
                    <li class="next last" style="display:none;"><a href="#">К концу</a></li>
                    <li class="next"><a href="#">Далее</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

Polyclinic/Views/Polyclinic/ViewRecordsToDoctor.cshtml
@{
    ViewBag.Title = "ViewRecordsToDoctor";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class='col-sm-7'>
        <div id="viewer-records-to-doctor-wizard">
            <ul>
                <li><a href="#tab1" data-toggle="tab">Выберете врача</a></li>
                <li><a href="#tab2" data-toggle="tab">Записи к врачу</a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane" id="tab1">
                    <div class="control-group">
                        <div class="dropdown">
                            <button id="doctor-selector" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="selector-title"></span>
                                <span class="caret"></span>
                            </button>
                            <ul id="doctors-menu" class="dropdown-menu" aria-labelledby="dLabel"></ul>
                        </div>
                    </div>
                </div>
                <div class="tab-pane" id="tab2">
                    <table id="doc-records" class="table table-bordered" data-height="300">
                        <thead>
                            <tr>
                                <th data-field="cabinet">Кабинет</th>
                                <th data-field="time">Время</th>
                                <th data-field="name">ФИО пациента</th>
                            </tr>
                        </thead>
                        <tbody class="doc-records-body"></tbody>
                    </table>
                </div>
                <ul class="pager wizard">
                    <li class="previous first" style="display:none;"><a href="#">К началу</a></li>
                    <li class="previous"><a href="#">Назад</a></li>
                    <li class="next last" style="display:none;"><a href="#">К концу</a></li>
                    <li class="next"><a href="#">Далее</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

Polyclinic/Views/Polyclinic/ViewTickets.cshtml
@{
    ViewBag.Title = "ViewTickets";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class='col-sm-7'>
        <div id="viewer-tickets-wizard">
            <ul>
                <li><a href="#tab1" data-toggle="tab">Введите номер карты</a></li>
                <li><a href="#tab2" data-toggle="tab">Талоны</a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane" id="tab1">
                    <div class="control-group">
                        <input type="text" class="form-control" id="card-id">
                    </div>
                </div>
                <div class="tab-pane" id="tab2">
                    <h3>Талоны к врачу:</h3>
                    <table id="tickets" class="table table-bordered" data-height="300">
                        <thead>
                            <tr>
                                <th data-field="name">ФИО врача</th>
                                <th data-field="cabinet">Кабинет</th>
                                <th data-field="time">Время</th>
                            </tr>
                        </thead>
                        <tbody class="tickets-body"></tbody>
                    </table>
                    <h3>Талоны на услуги:</h3>
                        <table id="tickets-service" class="table table-bordered" data-height="300">
                            <thead>
                                <tr>
                                    <th data-field="service">Усдуга</th>
                                    <th data-field="name">ФИО специалиста</th>
                                    <th data-field="cabinet">Кабинет</th>
                                    <th data-field="time">Дата</th>
                                    <th data-field="price">Цена</th>
                                </tr>
                            </thead>
                            <tbody class="tickets-service-body"></tbody>
                        </table>
                </div>
                <ul class="pager wizard">
                    <li class="previous first" style="display:none;"><a href="#">К началу</a></li>
                    <li class="previous"><a href="#">Назад</a></li>
                    <li class="next last" style="display:none;"><a href="#">К концу</a></li>
                    <li class="next"><a href="#">Далее</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>